# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af76bc976f153da20be241625599ae1298da73a78e44caa51a06bc5139871256a357e4beca2bbcb9fb492b3e3fbf3812e25a449aa12d9cf56b3a048f3e21f2ef

test:
  secret_key_base: a93491521160b58c26da6bf58820da0721313ba00feac7d70c950a7d673295f5cd2f820e5b9a08272b0452858fc143302ee2ebb15b35f40dfa3b758c99120ced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
